# Generated by Django 3.0.2 on 2020-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingdata',
            name='video',
        ),
        migrations.AddField(
            model_name='streamingdata',
            name='video_vf',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='streamingdata',
            name='video_vo',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
